# Generated by Django 5.1.6 on 2025-02-22 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('total_ram', models.IntegerField(help_text='Total RAM in GB')),
                ('total_cpu', models.IntegerField(help_text='Total CPU cores')),
                ('total_gpu', models.IntegerField(help_text='Total GPU units')),
                ('allocated_ram', models.IntegerField(default=0)),
                ('allocated_cpu', models.IntegerField(default=0)),
                ('allocated_gpu', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
