# Generated by Django 5.1.6 on 2025-02-23 05:39

from django.db import migrations

def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='Admin')
    Group.objects.get_or_create(name='Developer')
    Group.objects.get_or_create(name='Viewer')

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user'),
    ]

    operations = [
        migrations.RunPython(create_groups),
    ]
