# Generated by Django 5.1.6 on 2025-02-23 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_role_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='deployment',
            name='dependencies',
            field=models.ManyToManyField(blank=True, related_name='dependent_deployments', to='core.deployment'),
        ),
    ]
